-- ============================================================================
-- BC ERP-WMS V3.3 Phase 1 迁移脚本（超级简化版 - 分步执行）
-- ============================================================================
-- 说明：请逐步执行每个 STEP，观察执行结果
-- 如果某个步骤报错，停止并告诉我错误信息
-- ============================================================================

-- ============================================================================
-- STEP 1: 删除 product_spu 表（如果存在旧表，先删除）
-- ============================================================================
DROP TABLE IF EXISTS product_spu CASCADE;

-- ============================================================================
-- STEP 2: 创建 product_spu 表
-- ============================================================================
CREATE TABLE product_spu (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    spu_code VARCHAR(50) NOT NULL UNIQUE,
    spu_name VARCHAR(200) NOT NULL,
    category VARCHAR(100),
    brand VARCHAR(100),
    description TEXT,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 验证：执行后应该能看到 "CREATE TABLE" 成功提示

-- ============================================================================
-- STEP 3: 手动设置 product_spu 的序列，允许插入 ID=0
-- ============================================================================
-- PostgreSQL 的 GENERATED ALWAYS AS IDENTITY 默认不允许手动插入 ID
-- 我们需要临时修改序列
ALTER TABLE product_spu ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE product_spu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ============================================================================
-- STEP 4: 插入默认 SPU (ID=0)
-- ============================================================================
INSERT INTO product_spu (id, spu_code, spu_name, category, enabled)
VALUES (0, 'DEFAULT-SPU', 'Default Product Family (Legacy Data)', 'Uncategorized', true);

-- 验证：执行后应该能看到 "INSERT 0 1" 提示

-- ============================================================================
-- STEP 5: 查询验证 product_spu 表
-- ============================================================================
SELECT * FROM product_spu;

-- 预期结果：能看到 1 行记录，id=0, spu_code='DEFAULT-SPU'

-- ============================================================================
-- STEP 6: 重置序列（确保下次自动生成从 1 开始）
-- ============================================================================
SELECT setval('product_spu_id_seq', 1, false);

-- ============================================================================
-- 如果以上 STEP 1-6 都成功了，继续执行下面的步骤
-- ============================================================================

-- ============================================================================
-- STEP 7: 给 products 表添加 spu_id 列
-- ============================================================================
ALTER TABLE products ADD COLUMN IF NOT EXISTS spu_id BIGINT;

-- ============================================================================
-- STEP 8: 给 products 表添加 sku_name 列
-- ============================================================================
ALTER TABLE products ADD COLUMN IF NOT EXISTS sku_name VARCHAR(100);

-- ============================================================================
-- STEP 9: 给 products 表添加 specs 列
-- ============================================================================
ALTER TABLE products ADD COLUMN IF NOT EXISTS specs VARCHAR(500);

-- ============================================================================
-- STEP 10: 更新现有产品的 spu_id
-- ============================================================================
UPDATE products SET spu_id = 0 WHERE spu_id IS NULL;

-- ============================================================================
-- STEP 11: 更新现有产品的 sku_name
-- ============================================================================
UPDATE products SET sku_name = name WHERE sku_name IS NULL OR sku_name = '';

-- ============================================================================
-- STEP 12: 设置 spu_id 为 NOT NULL
-- ============================================================================
ALTER TABLE products ALTER COLUMN spu_id SET NOT NULL;

-- ============================================================================
-- STEP 13: 设置 sku_name 为 NOT NULL
-- ============================================================================
ALTER TABLE products ALTER COLUMN sku_name SET NOT NULL;

-- ============================================================================
-- STEP 14: 添加外键约束
-- ============================================================================
ALTER TABLE products
ADD CONSTRAINT fk_product_spu
FOREIGN KEY (spu_id)
REFERENCES product_spu(id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

-- ============================================================================
-- STEP 15: 创建索引
-- ============================================================================
CREATE INDEX idx_spu_id ON products(spu_id);

-- ============================================================================
-- STEP 16: 验证 products 表
-- ============================================================================
SELECT
    COUNT(*) AS total_products,
    COUNT(spu_id) AS products_with_spu_id,
    COUNT(sku_name) AS products_with_sku_name
FROM products;

-- 预期结果：三个数字应该相同

-- ============================================================================
-- STEP 17: 给 inventory_batch 表添加 location_code 列
-- ============================================================================
ALTER TABLE inventory_batch ADD COLUMN IF NOT EXISTS location_code VARCHAR(50);

-- ============================================================================
-- STEP 18: 从 locations 表同步 location_code
-- ============================================================================
UPDATE inventory_batch ib
SET location_code = l.location_code
FROM locations l
WHERE ib.location_id = l.id
  AND ib.location_code IS NULL;

-- ============================================================================
-- STEP 19: 为未分配库位的批次设置占位符
-- ============================================================================
UPDATE inventory_batch
SET location_code = 'PENDING'
WHERE location_code IS NULL AND location_id IS NULL;

-- ============================================================================
-- STEP 20: 为剩余的 NULL 值设置默认值
-- ============================================================================
UPDATE inventory_batch
SET location_code = 'UNASSIGNED'
WHERE location_code IS NULL;

-- ============================================================================
-- STEP 21: 设置 location_code 为 NOT NULL
-- ============================================================================
ALTER TABLE inventory_batch ALTER COLUMN location_code SET NOT NULL;

-- ============================================================================
-- STEP 22: 删除 batch_code 的唯一约束（如果存在）
-- ============================================================================
-- 先查找约束名
SELECT constraint_name
FROM information_schema.table_constraints
WHERE table_name = 'inventory_batch'
  AND constraint_type = 'UNIQUE';

-- 根据上面查询的结果，手动执行删除
-- 例如：ALTER TABLE inventory_batch DROP CONSTRAINT inventory_batch_batch_code_key;
-- 注意：约束名可能不同，请根据实际结果调整

-- ============================================================================
-- STEP 23: 创建新索引
-- ============================================================================
CREATE INDEX idx_batch_code ON inventory_batch(batch_code);
CREATE INDEX idx_batch_location ON inventory_batch(batch_code, location_code);
CREATE INDEX idx_location_code ON inventory_batch(location_code);

-- ============================================================================
-- STEP 24: 最终验证
-- ============================================================================
SELECT
    'product_spu' AS table_name,
    COUNT(*) AS row_count
FROM product_spu
UNION ALL
SELECT
    'products (spu_id not null)' AS table_name,
    COUNT(*) AS row_count
FROM products
WHERE spu_id IS NOT NULL
UNION ALL
SELECT
    'inventory_batch (location_code not null)' AS table_name,
    COUNT(*) AS row_count
FROM inventory_batch
WHERE location_code IS NOT NULL;

-- ============================================================================
-- 迁移完成！
-- ============================================================================
