-- ============================================================================
-- BC ERP-WMS V3.3 Phase 1 Complete Migration (完整幂等版)
-- ============================================================================
-- 用途：一次性完成所有迁移，可重复执行，自动跳过已完成的步骤
-- 执行方式：在 IntelliJ IDEA Database Console 中完整执行本脚本
-- 特性：
--   - 幂等性：多次执行不会出错
--   - 自动检测：跳过已存在的表、列、约束、索引
--   - 自动修复：自动清理冲突的约束
--   - 完整日志：每个步骤都有执行提示
-- ============================================================================

-- ============================================================================
-- PART 1: product_spu 表（产品家族表）
-- ============================================================================

-- 1.1 检查并创建 product_spu 表
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'product_spu') THEN
        CREATE TABLE product_spu (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            spu_code VARCHAR(50) NOT NULL UNIQUE,
            spu_name VARCHAR(200) NOT NULL,
            category VARCHAR(100),
            brand VARCHAR(100),
            description TEXT,
            enabled BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        RAISE NOTICE '✓ product_spu 表已创建';
    ELSE
        RAISE NOTICE '⊙ product_spu 表已存在，跳过创建';
    END IF;
END $$;

-- 1.2 修改序列允许手动插入 ID=0
DO $$
BEGIN
    -- 检查列是否为 GENERATED ALWAYS
    IF EXISTS (
        SELECT 1 FROM pg_attribute a
        JOIN pg_class c ON a.attrelid = c.oid
        WHERE c.relname = 'product_spu'
          AND a.attname = 'id'
          AND a.attidentity = 'a'  -- 'a' = ALWAYS
    ) THEN
        ALTER TABLE product_spu ALTER COLUMN id SET GENERATED BY DEFAULT;
        RAISE NOTICE '✓ product_spu.id 序列已修改为 BY DEFAULT';
    ELSE
        RAISE NOTICE '⊙ product_spu.id 序列已是 BY DEFAULT，跳过修改';
    END IF;
END $$;

-- 1.3 插入默认 SPU (ID=0)
INSERT INTO product_spu (id, spu_code, spu_name, category, enabled)
VALUES (0, 'DEFAULT-SPU', 'Default Product Family (Legacy Data)', 'Uncategorized', true)
ON CONFLICT (id) DO NOTHING;

-- 1.4 重置序列
SELECT setval('product_spu_id_seq', GREATEST(1, (SELECT COALESCE(MAX(id), 0) FROM product_spu)), false);

-- 1.5 验证 product_spu
DO $$
DECLARE
    spu_count INTEGER;
    default_spu_count INTEGER;
BEGIN
    SELECT COUNT(*), COUNT(*) FILTER (WHERE id = 0)
    INTO spu_count, default_spu_count
    FROM product_spu;

    RAISE NOTICE '✓ product_spu 表验证: 总数=%, 默认SPU=% (预期>=1)', spu_count, default_spu_count;

    IF default_spu_count = 0 THEN
        RAISE EXCEPTION '✗ 错误: 默认 SPU (ID=0) 不存在！';
    END IF;
END $$;

-- ============================================================================
-- PART 2: products 表（添加 SPU-SKU 字段）
-- ============================================================================

-- 2.1 添加 spu_id 列
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'products' AND column_name = 'spu_id'
    ) THEN
        ALTER TABLE products ADD COLUMN spu_id BIGINT;
        RAISE NOTICE '✓ products.spu_id 列已添加';
    ELSE
        RAISE NOTICE '⊙ products.spu_id 列已存在，跳过添加';
    END IF;
END $$;

-- 2.2 添加 sku_name 列
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'products' AND column_name = 'sku_name'
    ) THEN
        ALTER TABLE products ADD COLUMN sku_name VARCHAR(100);
        RAISE NOTICE '✓ products.sku_name 列已添加';
    ELSE
        RAISE NOTICE '⊙ products.sku_name 列已存在，跳过添加';
    END IF;
END $$;

-- 2.3 添加 specs 列
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'products' AND column_name = 'specs'
    ) THEN
        ALTER TABLE products ADD COLUMN specs VARCHAR(500);
        RAISE NOTICE '✓ products.specs 列已添加';
    ELSE
        RAISE NOTICE '⊙ products.specs 列已存在，跳过添加';
    END IF;
END $$;

-- 2.4 数据清洗：更新 spu_id
UPDATE products SET spu_id = 0 WHERE spu_id IS NULL;

-- 2.5 数据清洗：更新 sku_name
UPDATE products SET sku_name = name WHERE sku_name IS NULL OR sku_name = '';

-- 2.6 设置 NOT NULL 约束
DO $$
BEGIN
    -- 设置 spu_id NOT NULL
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'products' AND column_name = 'spu_id' AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE products ALTER COLUMN spu_id SET NOT NULL;
        RAISE NOTICE '✓ products.spu_id 已设置为 NOT NULL';
    ELSE
        RAISE NOTICE '⊙ products.spu_id 已是 NOT NULL，跳过设置';
    END IF;

    -- 设置 sku_name NOT NULL
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'products' AND column_name = 'sku_name' AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE products ALTER COLUMN sku_name SET NOT NULL;
        RAISE NOTICE '✓ products.sku_name 已设置为 NOT NULL';
    ELSE
        RAISE NOTICE '⊙ products.sku_name 已是 NOT NULL，跳过设置';
    END IF;
END $$;

-- 2.7 添加外键约束
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_product_spu' AND conrelid = 'products'::regclass
    ) THEN
        ALTER TABLE products
        ADD CONSTRAINT fk_product_spu
        FOREIGN KEY (spu_id)
        REFERENCES product_spu(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
        RAISE NOTICE '✓ 外键约束 fk_product_spu 已添加';
    ELSE
        RAISE NOTICE '⊙ 外键约束 fk_product_spu 已存在，跳过添加';
    END IF;
END $$;

-- 2.8 创建索引
CREATE INDEX IF NOT EXISTS idx_spu_id ON products(spu_id);

-- 2.9 验证 products 表
DO $$
DECLARE
    total_count INTEGER;
    spu_id_count INTEGER;
    sku_name_count INTEGER;
    null_spu_id INTEGER;
    null_sku_name INTEGER;
BEGIN
    SELECT
        COUNT(*),
        COUNT(spu_id),
        COUNT(sku_name),
        COUNT(*) FILTER (WHERE spu_id IS NULL),
        COUNT(*) FILTER (WHERE sku_name IS NULL OR sku_name = '')
    INTO total_count, spu_id_count, sku_name_count, null_spu_id, null_sku_name
    FROM products;

    RAISE NOTICE '✓ products 表验证: 总数=%, spu_id非空=%, sku_name非空=%',
        total_count, spu_id_count, sku_name_count;

    IF null_spu_id > 0 THEN
        RAISE EXCEPTION '✗ 错误: 存在 % 个产品的 spu_id 为 NULL！', null_spu_id;
    END IF;

    IF null_sku_name > 0 THEN
        RAISE EXCEPTION '✗ 错误: 存在 % 个产品的 sku_name 为空！', null_sku_name;
    END IF;
END $$;

-- ============================================================================
-- PART 3: inventory_batch 表（添加 location_code，移除 batch_code 唯一约束）
-- ============================================================================

-- 3.1 添加 location_code 列
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_batch' AND column_name = 'location_code'
    ) THEN
        ALTER TABLE inventory_batch ADD COLUMN location_code VARCHAR(50);
        RAISE NOTICE '✓ inventory_batch.location_code 列已添加';
    ELSE
        RAISE NOTICE '⊙ inventory_batch.location_code 列已存在，跳过添加';
    END IF;
END $$;

-- 3.2 数据清洗：从 locations 表同步 location_code
UPDATE inventory_batch ib
SET location_code = l.locationcode
FROM locations l
WHERE ib.location_id = l.id
  AND ib.location_code IS NULL;

-- 3.3 数据清洗：为未分配库位的批次设置占位符
UPDATE inventory_batch
SET location_code = 'PENDING'
WHERE location_code IS NULL AND location_id IS NULL;

-- 3.4 数据清洗：为剩余 NULL 值设置默认值
UPDATE inventory_batch
SET location_code = 'UNASSIGNED'
WHERE location_code IS NULL;

-- 3.5 设置 NOT NULL 约束
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'inventory_batch' AND column_name = 'location_code' AND is_nullable = 'YES'
    ) THEN
        ALTER TABLE inventory_batch ALTER COLUMN location_code SET NOT NULL;
        RAISE NOTICE '✓ inventory_batch.location_code 已设置为 NOT NULL';
    ELSE
        RAISE NOTICE '⊙ inventory_batch.location_code 已是 NOT NULL，跳过设置';
    END IF;
END $$;

-- 3.6 删除 batch_code 的所有唯一约束
DO $$
DECLARE
    constraint_rec RECORD;
    dropped_count INTEGER := 0;
BEGIN
    FOR constraint_rec IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'inventory_batch'::regclass
          AND contype = 'u'
          AND conname IN (
              SELECT constraint_name
              FROM information_schema.constraint_column_usage
              WHERE table_name = 'inventory_batch'
                AND column_name = 'batch_code'
          )
    LOOP
        EXECUTE format('ALTER TABLE inventory_batch DROP CONSTRAINT IF EXISTS %I', constraint_rec.conname);
        RAISE NOTICE '✓ 已删除唯一约束: %', constraint_rec.conname;
        dropped_count := dropped_count + 1;
    END LOOP;

    IF dropped_count = 0 THEN
        RAISE NOTICE '⊙ batch_code 上没有唯一约束，跳过删除';
    END IF;
END $$;

-- 3.7 删除 batch_code 的唯一索引
DO $$
DECLARE
    index_rec RECORD;
    dropped_count INTEGER := 0;
BEGIN
    FOR index_rec IN
        SELECT indexname
        FROM pg_indexes
        WHERE tablename = 'inventory_batch'
          AND indexdef LIKE '%UNIQUE%'
          AND indexdef LIKE '%batch_code%'
    LOOP
        EXECUTE format('DROP INDEX IF EXISTS %I', index_rec.indexname);
        RAISE NOTICE '✓ 已删除唯一索引: %', index_rec.indexname;
        dropped_count := dropped_count + 1;
    END LOOP;

    IF dropped_count = 0 THEN
        RAISE NOTICE '⊙ batch_code 上没有唯一索引，跳过删除';
    END IF;
END $$;

-- 3.8 创建新索引
CREATE INDEX IF NOT EXISTS idx_batch_code ON inventory_batch(batch_code);
CREATE INDEX IF NOT EXISTS idx_batch_location ON inventory_batch(batch_code, location_code);
CREATE INDEX IF NOT EXISTS idx_location_code ON inventory_batch(location_code);

-- 3.9 验证 inventory_batch 表
DO $$
DECLARE
    total_count INTEGER;
    null_location_code INTEGER;
BEGIN
    SELECT
        COUNT(*),
        COUNT(*) FILTER (WHERE location_code IS NULL)
    INTO total_count, null_location_code
    FROM inventory_batch;

    RAISE NOTICE '✓ inventory_batch 表验证: 总数=%, location_code为NULL=%',
        total_count, null_location_code;

    IF null_location_code > 0 THEN
        RAISE EXCEPTION '✗ 错误: 存在 % 个批次的 location_code 为 NULL！', null_location_code;
    END IF;
END $$;

-- ============================================================================
-- PART 4: 最终验证
-- ============================================================================

-- 4.1 综合验证报告
DO $$
DECLARE
    product_spu_exists BOOLEAN;
    default_spu_exists BOOLEAN;
    products_spu_id_exists BOOLEAN;
    products_sku_name_exists BOOLEAN;
    products_specs_exists BOOLEAN;
    inventory_location_code_exists BOOLEAN;
    fk_exists BOOLEAN;
    batch_code_unique_exists BOOLEAN;
BEGIN
    -- 检查各项
    product_spu_exists := EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'product_spu');
    default_spu_exists := EXISTS (SELECT 1 FROM product_spu WHERE id = 0);
    products_spu_id_exists := EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'spu_id');
    products_sku_name_exists := EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'sku_name');
    products_specs_exists := EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'specs');
    inventory_location_code_exists := EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'inventory_batch' AND column_name = 'location_code');
    fk_exists := EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_product_spu');
    batch_code_unique_exists := EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'inventory_batch'::regclass
          AND contype = 'u'
          AND pg_get_constraintdef(oid) LIKE '%batch_code%'
    );

    -- 输出报告
    RAISE NOTICE '';
    RAISE NOTICE '========================================';
    RAISE NOTICE '   V3.3 Phase 1 迁移验证报告';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'product_spu 表存在: %', CASE WHEN product_spu_exists THEN '✓' ELSE '✗' END;
    RAISE NOTICE 'product_spu 默认数据 (ID=0): %', CASE WHEN default_spu_exists THEN '✓' ELSE '✗' END;
    RAISE NOTICE 'products.spu_id 列存在: %', CASE WHEN products_spu_id_exists THEN '✓' ELSE '✗' END;
    RAISE NOTICE 'products.sku_name 列存在: %', CASE WHEN products_sku_name_exists THEN '✓' ELSE '✗' END;
    RAISE NOTICE 'products.specs 列存在: %', CASE WHEN products_specs_exists THEN '✓' ELSE '✗' END;
    RAISE NOTICE 'inventory_batch.location_code 列存在: %', CASE WHEN inventory_location_code_exists THEN '✓' ELSE '✗' END;
    RAISE NOTICE 'fk_product_spu 外键约束存在: %', CASE WHEN fk_exists THEN '✓' ELSE '✗' END;
    RAISE NOTICE 'batch_code 唯一约束已删除: %', CASE WHEN NOT batch_code_unique_exists THEN '✓' ELSE '✗' END;
    RAISE NOTICE '========================================';

    -- 检查是否全部通过
    IF product_spu_exists AND default_spu_exists AND
       products_spu_id_exists AND products_sku_name_exists AND products_specs_exists AND
       inventory_location_code_exists AND fk_exists AND NOT batch_code_unique_exists THEN
        RAISE NOTICE '✓✓✓ 迁移成功！所有检查项都已通过！';
    ELSE
        RAISE EXCEPTION '✗✗✗ 迁移失败！请检查上述失败项！';
    END IF;
END $$;

-- 4.2 数据统计
SELECT
    'product_spu' AS table_name,
    COUNT(*) AS row_count
FROM product_spu
UNION ALL
SELECT
    'products (spu_id not null)' AS table_name,
    COUNT(*) AS row_count
FROM products
WHERE spu_id IS NOT NULL
UNION ALL
SELECT
    'inventory_batch (location_code not null)' AS table_name,
    COUNT(*) AS row_count
FROM inventory_batch
WHERE location_code IS NOT NULL;

-- ============================================================================
-- 迁移完成！
-- ============================================================================
-- 如果看到 "✓✓✓ 迁移成功！所有检查项都已通过！"，说明迁移已成功完成。
-- 下一步：
-- 1. 在 IntelliJ IDEA 中刷新数据库连接（右键 → Refresh）
-- 2. 启动应用：mvn spring-boot:run
-- 3. 检查启动日志，确保无 Hibernate 错误
-- ============================================================================
