import { Alert, Button, Card, DatePicker, Descriptions, Empty, Form, Select, Space, Table, Tag, Typography } from 'antd';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { createPlatformAccessGrants, listPlatformAccessGrants, listPlatformManagedUsers, listPlatformTenants, revokePlatformAccessGrant, type PlatformAccessGrant, type PlatformManagedUser, type PlatformTenant } from './api';
import { platformAccessGrantStatus } from './platformAccessGrantStatus';

const DATASETS = ['users', 'roles', 'warehouses', 'products', 'inventory', 'sales_orders'];
export function PlatformAccessGrantPage(): JSX.Element {
 const { i18n } = useTranslation(); const english = i18n.language === 'en-US'; const [form] = Form.useForm();
 const [users,setUsers]=useState<PlatformManagedUser[]>([]); const [tenants,setTenants]=useState<PlatformTenant[]>([]); const [grants,setGrants]=useState<PlatformAccessGrant[]>([]); const [selected,setSelected]=useState<number>(); const [loading,setLoading]=useState(false); const [error,setError]=useState(false);
 const load=async(id?:number)=>{setLoading(true);setError(false);try{const [u,t]=await Promise.all([listPlatformManagedUsers(),listPlatformTenants(0,100)]);setUsers(u);setTenants(t.content);const target=id ?? selected;if(target){setSelected(target);setGrants(await listPlatformAccessGrants(target));}}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const submit=async(values:{capabilities:string[];tenantIds:number[];datasets:string[];range?:[any,any]})=>{if(!selected)return;setLoading(true);try{await createPlatformAccessGrants({platformUserId:selected,capabilities:values.capabilities as ('READ'|'EXPORT')[],tenantIds:values.tenantIds,datasets:values.datasets,effectiveFrom:values.range?.[0]?.toISOString(),expiresAt:values.range?.[1]?.toISOString()});form.resetFields();setGrants(await listPlatformAccessGrants(selected));}catch{setError(true)}finally{setLoading(false)}};
 return <main className="platform-home-content platform-audit-page"><div className="platform-section-heading"><div><Typography.Title level={2}>{english?'Delegated access':'委派授权'}</Typography.Title><Typography.Text type="secondary">{english?'Only the super administrator can grant or revoke read/export access.':'仅超级管理员可授予或撤销读取、导出权限；每项租户数据请求都会再次核验。'}</Typography.Text></div></div><Alert type="info" showIcon message={english?'No tenant or dataset wildcard is available. Unauthorised administrators cannot browse or export tenant data.':'不提供全部租户或全部数据集授权；未授权的平台管理员无法浏览或导出租户数据。'}/>{error?<Alert type="error" showIcon message={english?'Operation failed.':'操作失败，请检查授权范围和有效期。'}/>:null}<Card title={english?'Grant access':'授予访问权限'} loading={loading}><Space direction="vertical" size="middle" style={{width:'100%'}}><Select placeholder={english?'Choose a platform administrator':'选择平台管理员'} value={selected} onChange={(id)=>void load(id)} options={users.filter(u=>!u.superAdmin&&u.enabled).map(u=>({value:u.id,label:`${u.displayName} · ${u.email}`}))}/>{selected?<Form form={form} layout="vertical" onFinish={(v)=>void submit(v)}><Form.Item name="capabilities" label={english?'Capability':'能力'} rules={[{required:true}]}><Select mode="multiple" options={[{value:'READ',label:english?'Read':'读取'},{value:'EXPORT',label:english?'Export':'导出'}]}/></Form.Item><Form.Item name="tenantIds" label={english?'Tenants':'适用租户'} rules={[{required:true}]}><Select mode="multiple" options={tenants.map(t=>({value:t.id,label:`${t.displayName} · ${t.tenantCode}`}))}/></Form.Item><Form.Item name="datasets" label={english?'Datasets':'适用数据集'} rules={[{required:true}]}><Select mode="multiple" options={DATASETS.map(v=>({value:v,label:v}))}/></Form.Item><Form.Item name="range" label={english?'Effective period (default 30 days, max 90 days)':'有效期（默认 30 天，最长 90 天）'}><DatePicker.RangePicker showTime/></Form.Item><Button htmlType="submit" loading={loading} type="primary">{english?'Grant':'授予'}</Button></Form>:<Empty description={english?'Select an administrator first':'请先选择平台管理员'}/>}</Space></Card><Card title={english?'Existing grants':'现有授权'}>{selected?<Table rowKey="id" pagination={false} dataSource={grants} columns={[{title:english?'Capability':'能力',dataIndex:'capability',render:(v)=><Tag color="blue">{v}</Tag>},{title:english?'Tenant':'租户',dataIndex:'tenantName'},{title:english?'Dataset':'数据集',dataIndex:'datasetCode'},{title:english?'Expires':'到期时间',dataIndex:'expiresAt'},{title:english?'Status':'状态',render:(_,r:PlatformAccessGrant)=>{const status=platformAccessGrantStatus(r);return <Tag color={status==='ACTIVE'?'green':status==='SCHEDULED'?'blue':'default'}>{status}</Tag>}},{title:english?'Action':'操作',render:(_,r:PlatformAccessGrant)=>{const status=platformAccessGrantStatus(r);return <Button danger disabled={status==='REVOKED'||status==='EXPIRED'} onClick={()=>void revokePlatformAccessGrant(r.id).then(()=>load(selected))}>{english?'Revoke':'撤销'}</Button>}}]} />:<Empty/>}</Card></main>;
}
