package com.wms.system.util;

import com.wms.system.exception.BusinessException;
import com.wms.system.repository.InventoryBatchRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@DisplayName("BatchCodeGenerator Tests")
class BatchCodeGeneratorTest {

    @Mock private InventoryBatchRepository batchRepository;

    private BatchCodeGenerator batchCodeGenerator;

    @BeforeEach
    void setUp() {
        // Use a fixed salt and min-length for deterministic tests
        batchCodeGenerator = new BatchCodeGenerator("test-salt-for-unit-testing-32chars", 6);
    }

    // ========== generate ==========

    @Test
    @DisplayName("generate - returns non-null code of at least 6 chars")
    void testGenerate_ReturnsValidCode() {
        String code = batchCodeGenerator.generate(1L, 100L);

        assertThat(code).isNotNull();
        assertThat(code.length()).isGreaterThanOrEqualTo(6);
    }

    @Test
    @DisplayName("generate - returns different codes on successive calls (due to timestamp/random)")
    void testGenerate_ProducesDifferentCodes() throws InterruptedException {
        String code1 = batchCodeGenerator.generate(1L, 100L);
        Thread.sleep(2); // ensure timestamp differs
        String code2 = batchCodeGenerator.generate(1L, 100L);

        // Statistically extremely unlikely to be equal
        // (timestamp or random seed will differ)
        // We just verify format is valid for both
        assertThat(code1).isNotNull();
        assertThat(code2).isNotNull();
    }

    // ========== decode ==========

    @Test
    @DisplayName("decode - decodes to 3 elements [productId, timestamp, random]")
    void testDecode_Returns3Elements() {
        String code = batchCodeGenerator.generate(42L, 7L);
        long[] decoded = batchCodeGenerator.decode(code);

        assertThat(decoded).hasSize(3);
        assertThat(decoded[0]).isEqualTo(42L); // productId
    }

    @Test
    @DisplayName("decode - empty array for invalid code")
    void testDecode_InvalidCode() {
        long[] decoded = batchCodeGenerator.decode("INVALID!@#");

        // Hashids returns empty array for codes with invalid characters
        assertThat(decoded).isEmpty();
    }

    // ========== isValidFormat ==========

    @Test
    @DisplayName("isValidFormat - returns true for valid generated code")
    void testIsValidFormat_Valid() {
        String code = batchCodeGenerator.generate(1L, 1L);

        assertThat(batchCodeGenerator.isValidFormat(code)).isTrue();
    }

    @Test
    @DisplayName("isValidFormat - returns false for null")
    void testIsValidFormat_Null() {
        assertThat(batchCodeGenerator.isValidFormat(null)).isFalse();
    }

    @Test
    @DisplayName("isValidFormat - returns false for empty string")
    void testIsValidFormat_Empty() {
        assertThat(batchCodeGenerator.isValidFormat("")).isFalse();
    }

    @Test
    @DisplayName("isValidFormat - returns false for code that decodes to wrong length")
    void testIsValidFormat_WrongLength() {
        // A code not generated by us likely decodes to 0 or wrong number of elements
        // We use the Hashids library directly to generate a 2-element code (not 3)
        // The simplest way: check with a manually crafted code
        // Instead, we verify that a code not produced by our generator returns false
        assertThat(batchCodeGenerator.isValidFormat("!@#$%^")).isFalse();
    }

    // ========== generateUnique ==========

    @Test
    @DisplayName("generateUnique - returns code when no collision")
    void testGenerateUnique_Success() {
        when(batchRepository.existsByBatchCode(anyString())).thenReturn(false);

        String code = batchCodeGenerator.generateUnique(1L, 100L, batchRepository);

        assertThat(code).isNotNull();
        assertThat(code.length()).isGreaterThanOrEqualTo(6);
    }

    @Test
    @DisplayName("generateUnique - retries on collision and returns unique code on second attempt")
    void testGenerateUnique_RetryOnCollision() {
        // First code exists, second doesn't
        when(batchRepository.existsByBatchCode(anyString()))
                .thenReturn(true)   // attempt 1: collision
                .thenReturn(false); // attempt 2: unique

        String code = batchCodeGenerator.generateUnique(1L, 100L, batchRepository);

        assertThat(code).isNotNull();
    }

    @Test
    @DisplayName("generateUnique - throws BusinessException after 3 failed attempts")
    void testGenerateUnique_ExhaustsRetries() {
        // All attempts collide
        when(batchRepository.existsByBatchCode(anyString())).thenReturn(true);

        assertThatThrownBy(() -> batchCodeGenerator.generateUnique(1L, 100L, batchRepository))
                .isInstanceOf(BusinessException.class);
    }
}
