package com.wms.system;

import com.wms.system.entity.User;
import com.wms.system.repository.UserRepository;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.retry.annotation.EnableRetry;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.annotation.Transactional;

import java.util.TimeZone;

/**
 * WMS System Main Application
 *
 * Architecture Standards:
 * - Backend Timezone: UTC (absolute time storage for international systems)
 * - Frontend: Converts UTC to local timezone for display
 * - JPA Auditing: Enabled via JpaAuditingConfig
 * - Retry Mechanism: Enabled for optimistic lock conflict handling
 * - Database: PostgreSQL 16 with UTF-8 encoding
 * - Security: Spring Security + JWT authentication
 *
 * @author WMS Team
 * @since 2025-01-09
 * @version 3.0 (Security Layer + Auto User Initialization)
 */
@Slf4j
@SpringBootApplication
@EnableRetry  // Enable retry mechanism for @Retryable in InventoryService
@EnableTransactionManagement
public class WmsSystemApplication {

    public static void main(String[] args) {
        SpringApplication.run(WmsSystemApplication.class, args);
    }

    /**
     * Force JVM timezone to UTC on application startup
     *
     * International Architecture Decision:
     * - Backend stores absolute time in UTC (no timezone ambiguity)
     * - Frontend displays time in user's local timezone
     * - Supports multi-region deployments (China, UK, US, etc.)
     *
     * This ensures consistent time handling regardless of server location.
     */
    @PostConstruct
    public void init() {
        TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
        System.out.println("=======================================================");
        System.out.println("=== WMS System Started Successfully                 ===");
        System.out.println("=== Backend Timezone: UTC (International Standard)  ===");
        System.out.println("=======================================================");
    }

    /**
     * �?Auto Initialize Admin User on Startup
     *
     * EMERGENCY FIX:
     * - Automatically creates or resets admin user on every startup
     * - Ensures password hash is generated by current BCryptPasswordEncoder
     * - Prevents manual hash copy-paste encoding issues
     *
     * Admin Credentials:
     * - Username: admin
     * - Password: password123
     * - Role: SUPER_ADMIN (assigned via Flyway migration V3_3)
     *
     * v3.3 Multi-Role System:
     * - User roles are now assigned via sys_user_role junction table
     * - Flyway migration V3_3__multi_role_migration.sql handles role assignment
     * - This method only creates the User entity without role assignment
     *
     * This CommandLineRunner executes AFTER all beans are initialized.
     * It uses the same PasswordEncoder configured in SecurityConfig.
     *
     * @param userRepository User repository for database operations
     * @param passwordEncoder BCrypt password encoder from SecurityConfig
     * @return CommandLineRunner that initializes admin user
     */
    @Bean
    @Transactional
    public CommandLineRunner initAdminUser(UserRepository userRepository,
                                            PasswordEncoder passwordEncoder) {
        return args -> {
            System.out.println("\n=======================================================");
            System.out.println("=== [STARTUP] Auto Initialize Admin User            ===");
            System.out.println("=======================================================");

            String adminUsername = "admin";
            String adminPassword = "password123";

            try {
                // Check if admin user exists
                User adminUser = userRepository.findByUsername(adminUsername).orElse(null);

                if (adminUser == null) {
                    // Admin user does not exist, create new one
                    System.out.println("[INFO] Admin user not found, creating new admin user...");

                    String encodedPassword = passwordEncoder.encode(adminPassword);

                    adminUser = User.builder()
                        .username(adminUsername)
                        .password(encodedPassword)
                        // v3.3 Multi-Role System: Role assignment now handled via sys_user_role table
                        // Flyway migration V3_3__multi_role_migration.sql assigns SUPER_ADMIN role
                        .displayName("System Administrator")
                        .enabled(true)
                        .remark("Auto-created admin user on system startup")
                        .build();

                    userRepository.save(adminUser);

                    System.out.println("[SUCCESS] Admin user created successfully!");
                    System.out.println("  ├─ Username: " + adminUsername);
                    System.out.println("  - Password: initialized (hidden)");
                    System.out.println("  ├─ Role: SUPER_ADMIN (assigned via Flyway migration)");

                } else {
                    // Admin user exists, FORCE reset password
                    System.out.println("[INFO] Admin user found, FORCE resetting password...");
                    System.out.println("  ├─ User ID: " + adminUser.getId());

                    String newEncodedPassword = passwordEncoder.encode(adminPassword);
                    adminUser.setPassword(newEncodedPassword);

                    userRepository.save(adminUser);

                    System.out.println("[SUCCESS] Admin password reset successfully!");
                    System.out.println("  ├─ Username: " + adminUsername);
                    System.out.println("  - New password: updated (hidden)");
                }

                // Verify password encoding
                boolean passwordMatches = passwordEncoder.matches(adminPassword, adminUser.getPassword());

                System.out.println("\n[VERIFICATION] Password encoding verification:");
                System.out.println("  └─ Password Matches: " + (passwordMatches ? "�?YES" : "�?NO"));

                if (!passwordMatches) {
                    System.err.println("[ERROR] Password verification FAILED! Hash mismatch!");
                    throw new RuntimeException("Password encoding verification failed!");
                }

                System.out.println("\n=======================================================");
                System.out.println("=== [STARTUP] Admin User Initialization Complete   ===");
                System.out.println("=== Admin credentials are configured (hidden).      ===");
                System.out.println("=======================================================\n");

            } catch (Exception e) {
                System.err.println("[ERROR] Failed to initialize admin user!");
                System.err.println("Error message: " + e.getMessage());
                e.printStackTrace();
                throw new RuntimeException("Admin user initialization failed", e);
            }
        };
    }
}
